name: Run Python Script in Docker

on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'Numele fișierului Python de rulat'
        required: true
        default: 'hello.py'  # Poți seta un nume implicit

jobs:
  run-python-in-docker:
    runs-on: ubuntu-latest

    steps:
      # Pasul 1: Checkout codul sursă din repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Pasul 2: Rulează scriptul Python folosind Docker
      - name: Run Python script in Docker
        run: |
          docker run --rm -v "$(pwd)":/app python:3.10-slim bash -c "pip install requests && python /app/${{ github.event.inputs.filename }}"
